project_id: '14'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'
base_url: https://inreach.crowdin.com
base_path: '.'
preserve_hierarchy: false
files:
  - source: /public/locales/en/*.json
    translation: /public/locales/%two_letters_code%/%original_file_name%
    type: i18next_json
    update_option: 'update_as_unapproved'
