import { type Prisma } from '@prisma/client'

export const categories: Prisma.StoryCategoryCreateManyInput[] = [
	{
		id: 'clienra1i0000pexbs0j5xjhl',
		categoryEN: 'BIPOC',
		categoryES: 'BIPOC',
		categoryFR: 'BIPOC',
		image: 'bipoc',
		order: 1,
		tag: 'bipoc',
		imageAltEN: 'Diverse group of people smiling',
		imageAltES: 'Grupo diverso de personas sonriendo',
		imageAltFR: 'Groupe divers de personnes souriantes',
	},
	{
		id: 'clienra1i0001pexbc72b9hyj',
		categoryEN: 'Disabled',
		categoryES: 'Con discapacidad',
		categoryFR: 'Personne handicapée',
		image: 'disabled',
		tag: 'disabled',
		order: 2,
		imageAltEN: 'Person using a wheelchair outdoors',
		imageAltES: 'Persona en silla de ruedas al aire libre',
		imageAltFR: "Personne en fauteuil roulant à l'extérieur",
	},
	{
		id: 'clienra1i0002pexbm17yqg2d',
		categoryEN: 'Elder',
		categoryES: 'Persona mayor',
		categoryFR: 'Personne âgée',
		image: 'elder',
		tag: 'elder',
		order: 4,
		imageAltEN: 'Smiling elderly person',
		imageAltES: 'Persona mayor sonriendo',
		imageAltFR: 'Personne âgée souriante',
	},
	{
		id: 'clienra1i0003pexbvo2gu720',
		categoryEN: 'Immigrant',
		categoryES: 'Inmigrante',
		categoryFR: 'Immigré(e)',
		image: 'immigrant',
		tag: 'immigrant',
		order: 3,
		imageAltEN: 'Family arriving in a new country',
		imageAltES: 'Familia llegando a un nuevo país',
		imageAltFR: 'Famille arrivant dans un nouveau pays',
	},
	{
		id: 'clienra1i0004pexbkht4nc39',
		categoryEN: 'Transmasc/Nonbinary',
		categoryES: 'Transmasculino/Nonbinario',
		categoryFR: 'Transmasculine/Nonbinaire',
		image: 'transmasc',
		tag: 'transmasc-nonbinary',
		order: 7,
		imageAltEN: 'Person identifying as transmasculine or nonbinary',
		imageAltES: 'Persona que se identifica como transmasculina o no binaria',
		imageAltFR: "Personne s'identifiant comme transmasculine ou non-binaire",
	},
	{
		id: 'clienra1i0005pexby9upd67c',
		categoryEN: 'Queer',
		categoryES: 'Queer',
		categoryFR: 'Queer',
		image: 'queer',
		order: 5,
		tag: 'queer',
		imageAltEN: 'Rainbow flag representing queer community',
		imageAltES: 'Bandera arcoíris que representa la comunidad queer',
		imageAltFR: 'Drapeau arc-en-ciel représentant la communauté queer',
	},
	{
		id: 'clienra1i0006pexbks2nzu97',
		categoryEN: 'Trans man',
		categoryES: 'Hombre trans',
		categoryFR: 'Homme trans',
		image: 'transman',
		tag: 'transman',
		order: 6,
		imageAltEN: 'Transgender man smiling confidently',
		imageAltES: 'Hombre transgénero sonriendo con confianza',
		imageAltFR: 'Homme transgenre souriant avec confiance',
	},
]
