import { type Prisma } from '@prisma/client'

export const categories: Prisma.StoryCategoryCreateManyInput[] = [
	{
		id: 'clienra1i0000pexbs0j5xjhl',
		categoryEN: 'BIPOC',
		categoryES: 'BIPOC',
		image: 'bipoc',
		order: 1,
		tag: 'bipoc',
	},
	{
		id: 'clienra1i0001pexbc72b9hyj',
		categoryEN: 'Disabled',
		categoryES: 'Con discapacidad',
		image: 'disabled',
		tag: 'disabled',
		order: 2,
	},
	{
		id: 'clienra1i0002pexbm17yqg2d',
		categoryEN: 'Elder',
		categoryES: 'Persona mayor',
		image: 'elder',
		tag: 'elder',
		order: 4,
	},
	{
		id: 'clienra1i0003pexbvo2gu720',
		categoryEN: 'Immigrant',
		categoryES: 'Inmigrante',
		image: 'immigrant',
		tag: 'immigrant',
		order: 3,
	},
	{
		id: 'clienra1i0004pexbkht4nc39',
		categoryEN: 'Transmasc/Nonbinary',
		categoryES: 'Transmasculino/Nonbinario',
		image: 'transmasc',
		tag: 'transmasc-nonbinary',
		order: 7,
	},
	{
		id: 'clienra1i0005pexby9upd67c',
		categoryEN: 'Queer',
		categoryES: 'Queer',
		image: 'queer',
		order: 5,
		tag: 'queer',
	},
	{
		id: 'clienra1i0006pexbks2nzu97',
		categoryEN: 'Trans man',
		categoryES: 'Hombre trans',
		image: 'transman',
		tag: 'transman',
		order: 6,
	},
]
