import { type Prisma } from '@prisma/client'

// import { partnerImages } from '~/data/partners'

export const partnerData: Prisma.PartnerOrgCreateManyInput[] = [
	{
		name: 'GLAAD',
		tag: 'glaad',
		order: 1,
		// imageSrc: partnerImages.glaad.src,
		// height: partnerImages.glaad.height,
		// width: partnerImages.glaad.width,
		href: 'https://www.glaad.org/',
	},
	{
		name: 'Lambda Legal',
		tag: 'lambdaLegal',
		order: 2,
		// imageSrc: partnerImages.lambdaLegal.src,
		// height: partnerImages.lambdaLegal.height,
		// width: partnerImages.lambdaLegal.width,
		href: 'https://www.lambdalegal.org/',
	},
	{
		name: 'SAGE',
		tag: 'sage',
		order: 3,
		// imageSrc: partnerImages.sage.src,
		// height: partnerImages.sage.height,
		// width: partnerImages.sage.width,
		href: 'https://www.sageusa.org/',
	},
	{
		name: 'Immigration Equality',
		tag: 'immigrationEquality',
		order: 4,
		// imageSrc: partnerImages.immigrationEquality.src,
		// height: partnerImages.immigrationEquality.height,
		// width: partnerImages.immigrationEquality.width,
		href: 'https://immigrationequality.org/',
	},
	{
		name: 'NQAPIA',
		tag: 'nqapia',
		order: 5,
		// imageSrc: partnerImages.nqapia.src,
		// height: partnerImages.nqapia.height,
		// width: partnerImages.nqapia.width,
		href: 'https://www.nqapia.org/',
	},
	{
		name: 'KYLP',
		tag: 'kylp',
		order: 6,
		// imageSrc: partnerImages.kylp.src,
		// height: partnerImages.kylp.height,
		// width: partnerImages.kylp.width,
		href: 'https://www.kylp.org/',
	},
	{
		name: 'MTPC',
		tag: 'mtpc',
		order: 7,
		// imageSrc: partnerImages.mtpc.src,
		// height: partnerImages.mtpc.height,
		// width: partnerImages.mtpc.width,
		href: 'https://www.masstpc.org/',
	},
	{
		name: 'Oasis Legal',
		tag: 'oasisLegal',
		order: 8,
		// imageSrc: partnerImages.oasisLegal.src,
		// height: partnerImages.oasisLegal.height,
		// width: partnerImages.oasisLegal.width,
		href: 'https://www.oasislegalservices.org/',
	},
	{
		name: 'Stand With Trans',
		tag: 'standWithTrans',
		order: 9,
		// imageSrc: partnerImages.standWithTrans.src,
		// height: partnerImages.standWithTrans.height,
		// width: partnerImages.standWithTrans.width,
		href: 'https://standwithtrans.org/',
	},
	{
		name: 'TAVA',
		tag: 'tava',
		order: 10,
		// imageSrc: partnerImages.tava.src,
		// height: partnerImages.tava.height,
		// width: partnerImages.tava.width,
		href: 'https://www.transveteran.org/',
	},
]
