name: 'PR Auto Approve'
on:
  pull_request:
    types: [review_requested]

permissions:
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: github/privileged-requester@3bfe4fe11beb79a205f0143769d3035d728cec2d # v2.2.0
        if: ${{ github.event.requested_reviewer.login == 'InReach-svc'}}
        with:
          github_token: ${{ secrets.GH_ACT_PAT }}
          path: .github/autoapprove-config.yaml
          prCreator: ${{ github.event.pull_request.user.login }}
          prNumber: ${{ github.event.pull_request.number }}
          checkCommits: 'false'
          checkDiff: 'false'
          checkLabels: 'false'
