name: 'Chromatic'
on:
  push:
  workflow_dispatch:
    inputs:
      sha:
        description: The SHA-1 hash referring to the commit to check.
        required: true
      ref:
        description: The head branch associated with the pull request.
        required: true
jobs:
  chromatic-deployment:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
      - name: Publish to Chromatic
        uses: chromaui/action@2a0b63f30233c48591844a46d451b9cf68128186 # v18
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          skip: '@(renovate/**|l10_**)'
