name: Lint & format

on:
  push:
    branches-ignore: [dev, main, renovate/*]

jobs:
  lintformat:
    # env:
    # GITHUB_TOKEN: ${{ secrets.GH_ACT_PAT }}
    name: 'Lint & format'
    runs-on: ubuntu-latest
    steps:
      # Setup steps
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_KEY }}
          git_user_signingkey: true
          git_config_global: true
          git_commit_gpgsign: true

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false
          # standalone: true

      - name: Install Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Lint projects
        run: pnpm lint:fix
        if: always()
        id: lint

      - name: Format projects
        run: pnpm format
        if: always()
        id: format

      # Commit changes
      - name: Commit changed files
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        if: always()
        with:
          message: 'chore: lint & format'
          commit: --signoff --no-verify
          committer_name: InReach [bot]
          committer_email: 108850934+InReach-svc@users.noreply.github.com
          author_name: InReach [bot]
          author_email: 108850934+InReach-svc@users.noreply.github.com
