name: Lint & format

on:
  push:
    branches-ignore: [dev, main, renovate/*]

jobs:
  lintformat:
    # env:
    # GITHUB_TOKEN: ${{ secrets.GH_ACT_PAT }}
    name: 'Lint & format'
    runs-on: ubuntu-latest
    steps:
      # Setup steps
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_KEY }}
          git_user_signingkey: true
          git_config_global: true
          git_commit_gpgsign: true

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false
          # standalone: true

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Lint projects
        run: pnpm lint:fix
        if: always()
        id: lint

      - name: Format projects
        run: pnpm format
        if: always()
        id: format

      # Commit changes
      - name: Commit changed files
        uses: EndBug/add-and-commit@cc9c08ba6c8df3b93a8f2db63e89b98368ae2ae8 # v11
        if: always()
        with:
          message: 'chore: lint & format'
          commit: --signoff --no-verify
          committer_name: InReach [bot]
          committer_email: 108850934+InReach-svc@users.noreply.github.com
          author_name: InReach [bot]
          author_email: 108850934+InReach-svc@users.noreply.github.com
