---
name: PR Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened, edited]

jobs:
  pr_labels:
    name: 🏭 Verify labels
    runs-on: ubuntu-latest
    steps:
      - name: 🏷 Verify PR has a valid label
        uses: mheap/github-action-required-labels@fb29a14a076b0f74099f6198f77750e8fc236016 # v5
        with:
          labels: 'breaking-change, bugfix, documentation, enhancement, refactor, performance, new-feature, maintenance, ci, dependencies, translations, changelog-ignore'
          mode: minimum
          count: 1
  pr_wip_check:
    runs-on: ubuntu-latest
    name: 🏭 Check for blocking labels
    steps:
      - name: 🏷 Check PR for a merge-blocking label
        uses: tim-actions/wip-check@8c84f5987215d49440b86475062d61e4f099e1b7 # main branch
        with:
          labels: '["do-not-merge", "wip", "rfc", "blocked"]'
          keywords: '["WIP", "wip", "RFC", "rfc"]'
  pr_monorepo_label:
    name: 🏭 Label PR With Repo(s)
    runs-on: ubuntu-latest
    if: contains(fromJson('["main", "l10_*"]'), github.base_ref) != true
    steps:
      - name: 🏷 Apply repo labels
        uses: tinkurlab/monorepo-pr-labeler-action@026d1e71df075b29ee3986875bfbb8a5b5d969f1 # 4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACT_PAT }}
          BASE_DIRS: 'apps|packages'
        with:
          prefix: '📦'
          separator: ' '
