name: Sync branch
on:
  push:
    branches:
      - main
jobs:
  sync-branch:
    name: Update dev branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - uses: connor-baer/action-sync-branch@ad8cff0bc606b7d6b8287dde859b0947b9c531dd # main
        with:
          branch: dev
          token: ${{ secrets.GH_ACT_PAT }}
          force: false
